name: Resolve the submodule by name in the repository.
inputs:
  name:
    required: true
    description: "The submodule name, found in the section name in .gitmodules"

outputs:
  path:
    description: "Path of the submodule relative to superproject"
    value: "${{ steps.gitmodules.outputs.path }}"
  ref:
    description: "Ref of the commit in the submodule, that the superproject holds"
    value: "${{ steps.head.outputs.ref }}"
  url:
    value: "${{ steps.gitmodules.outputs.url }}"
runs:
  using: composite
  steps:
    - id: gitmodules
      shell: bash
      env:
        name: ${{ inputs.name }}
      run: |
        git config -f .gitmodules --get 'submodule.${{ env.name }}.path' | sed -En "/^$/q1; s/^(.*)$/path=\1/;p;" >> $GITHUB_OUTPUT
        git config -f .gitmodules --get 'submodule.${{ env.name }}.url' | sed -En "/^$/q1; s/^(.*)$/url=\1/;p;" >> $GITHUB_OUTPUT
    - name: Rejects invalid name
      if: ${{ env.path == '' }}
      shell: bash
      env:
        name: ${{ inputs.name }}
        path: ${{ steps.gitmodules.outputs.path }}
      run: |
        echo "::error::${{ format('the name {0} is ambiguous in the HEAD.', env.name) }}"
        exit 1
    - id: head
      if: ${{ success() }}
      name: Describes the the submodule ref
      shell: bash
      env:
        path: ${{ steps.gitmodules.outputs.path }}
      run: |
        git ls-tree --format 'path=%(path)' HEAD "${{ env.path }}" >> $GITHUB_OUTPUT
        git ls-tree --format 'ref=%(objectname)' HEAD "${{ env.path }}" >> $GITHUB_OUTPUT
 